config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'hi' => "welcome#hi", as: :welcome_hi
  get 'comunidad' => "comunidad#show", as: :comunidad_show

  root "dashboards#show"
  devise_for :admins, controllers: { sessions: 'admin/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :edit, :update] do
    resources :recommended_posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :responses, only: [:create]
  end

  resources :tags, only: [:show, :edit, :update]

  get "me/bookmarks" => "dashboards#bookmarks", as: :dashboard_bookmarks
  get "top-stories" => "dashboards#top_stories", as: :top_stories
  get "me/stories/drafts" => "stories#drafts", as: :stories_drafts
  get "me/stories/public" => "stories#published", as: :stories_published
  get "search" => "search#show", as: :search
  get "search/users" => "search#users", as: :search_users
  post "posts/create_and_edit" => "posts#create_and_edit", as: :post_create_and_edit
  post "/" => "posts#create", as: :posts_create_dashboard 

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :featured_tags, only: [:create, :destroy]
    resources :featured_posts, only: [:create, :destroy]
  end

  namespace :api do
    resources :notifications, only: [:index] do
      post :mark_as_touched, on: :collection
      post :mark_all_as_read, on: :collection
      post :mark_as_read, on: :member
    end

    get "autocomplete" => "search_autocomplete#index"

    resources :posts, only: [:create, :update, :destroy]
    resources :users, only: [:show]
    resources :likers, only: [:index]
    resources :tag_followers, only: [:index]
    resources :followers, only: [:index]
    resources :following, only: [:index]
    resources :following_tags, only: [:index]
    resources :tags, only: [:create]
    resources :follow_suggestions, only: [:index]

    resources :posts, only: [] do
      resource :likes, only: [:create, :destroy], module: :posts
      resource :bookmarks, only: [:create, :destroy], module: :posts
    end

    resources :responses, only: [] do
      resource :likes, only: [:create, :destroy], module: :responses
      resource :bookmarks, only: [:create, :destroy], module: :responses
    end

    post    "relationships" => "relationships#create"
    delete  "relationships" => "relationships#destroy"
    post    "interests" => "interests#create"
    delete  "interests" => "interests#destroy"
  end

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq' 
  end
end

app/views/shared/_facebook_sdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1580607045584905',
      xfbml      : true,
      version    : 'v2.5'
    });
  };
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_inline_editor.html.erb
<div class="inline-editor" id="inline-editor" data-page="inline-editor">
  
  <div id="cont-main" class="cont-main">
    <div class="editor-metadata">
      <%= avatar_for(current_user, size: 40) %>
      <strong class="editor-username"><%= current_user.username %></strong>
    </div>

    <div id="choose">
      <div id="short" class="options-form back-options">Algo corto</div>
      <div id="large" class="options-form">Algo largo</div>
    </div>
  </div>
  
  <div id="short-form" style="display: inline;">
    <%= form_for Post.create, url: posts_create_dashboard_path, html: { multipart: true, class: "editor-form", autocomplete: "off" } do |f| %>
      <div class="form-group hide" id="title-dashS">
        <%= f.text_field :title, class: 'editor-title', placeholder: 'Título', data: { behavior: "autosave" }, onfocus: "this.value = this.value;" %>
      </div>

      <div class="form-group">
        <%= f.text_area :body, class: 'medium-editable post-body', id: 'editor-body' %> 
      </div>

      <button class="button green-border-button" data-behavior="publish-button">Publicar</button>
      <button class='button green-border-button cancel-button' data-behavior="editor-cancel">Cancelar</button>
    <% end %>
  </div>

  <div id="large-form" style="display: none;">
    <%= form_for @dashboard.new_post, url: post_create_and_edit_path, html: { multipart: true, class: "editor-form", autocomplete: "off" } do |f| %>

      <div class="form-group hide" id="title-dashL">
        <%= f.text_field :title, class: 'editor-title', placeholder: 'Título', data: { behavior: "autosave" }, onfocus: "this.value = this.value;" %>
      </div>

      <div id="body-large" class="form-group">
        <%= f.text_area :body, class: 'medium-editable post-body', id: 'editor-body' %> 
      </div>

      <%= f.submit "Pantalla completa", class: 'button green-inner-button go-full-screen' %>
      <button class='button green-border-button cancel-button' data-behavior="editor-cancel">Cancelar</button>
    <% end %>
  </div>
</div>